name: Build Android APK

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm ci

    - name: Build web application
      run: npm run build

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Build Debug APK
      working-directory: android
      run: ./gradlew assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: furnili-management-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk

   - name: Decode Keystore (for signed release)
  env:
    KEYSTORE: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
  if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')) && env.KEYSTORE != ''
  run: |
    echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/release.keystore
    
    - name: Build Release APK
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
      working-directory: android
      env:
        RELEASE_STORE_FILE: release.keystore
        RELEASE_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        RELEASE_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      run: ./gradlew assembleRelease

    - name: Upload Signed Release APK
  env:
    KEYSTORE: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
  if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')) && env.KEYSTORE != ''
  uses: actions/upload-artifact@v4
      with:
        name: furnili-management-release-signed-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        
- name: Upload Unsigned Release APK
  env:
    KEYSTORE: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
  if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')) && env.KEYSTORE == ''
      uses: actions/upload-artifact@v4
      with:
        name: furnili-management-release-unsigned-apk
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Build Release Bundle (AAB)
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
      working-directory: android
      env:
        RELEASE_STORE_FILE: release.keystore
        RELEASE_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        RELEASE_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      run: ./gradlew bundleRelease

    - name: Upload Release Bundle (AAB)
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v4
      with:
        name: furnili-management-release-aab
        path: android/app/build/outputs/bundle/release/app-release.aab
