name: Build Android APK

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HAS_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Java 17
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
          PATH: ${{ steps.setup-java.outputs.path }}/bin:${{ env.PATH }}

      - name: Force Java 17 for Gradle
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.java.home=${{ steps.setup-java.outputs.path }}" >> ~/.gradle/gradle.properties

      - name: Install dependencies
        run: npm ci

      - name: Build web application
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: furnili-management-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Decode Keystore (for signed release)
        if: env.HAS_KEYSTORE != ''
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "${ANDROID_KEYSTORE_BASE64}" | base64 -d > android/release.keystore

      - name: Build Release APK
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        working-directory: android
        env:
          RELEASE_STORE_FILE: release.keystore
          RELEASE_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Upload Signed Release APK
        if: env.HAS_KEYSTORE != ''
        uses: actions/upload-artifact@v4
        with:
          name: furnili-management-release-signed-apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload Unsigned Release APK
        if: env.HAS_KEYSTORE == ''
        uses: actions/upload-artifact@v4
        with:
          name: furnili-management-release-unsigned-apk
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Build Release Bundle (AAB)
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        working-directory: android
        env:
          RELEASE_STORE_FILE: release.keystore
          RELEASE_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: ./gradlew bundleRelease

      - name: Upload Release Bundle (AAB)
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: furnili-management-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
